"""empty message

Revision ID: 0e471943d4de
Revises: 4c759d4bbd9d
Create Date: 2025-02-22 12:06:37.975925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e471943d4de'
down_revision = '4c759d4bbd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_advice',
    sa.Column('plan_advice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('plan_advice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_advice')
    # ### end Alembic commands ###
