"""empty message

Revision ID: 22ba3a87ef65
Revises: ce408e1c76b9
Create Date: 2025-03-10 00:26:57.908034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22ba3a87ef65'
down_revision = 'ce408e1c76b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_item',
    sa.Column('knowledge_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_graph_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graph.knowledge_graph_id'], ),
    sa.PrimaryKeyConstraint('knowledge_item_id')
    )
    op.create_table('knowledge_relation',
    sa.Column('knowledge_relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_graph_id', sa.Integer(), nullable=False),
    sa.Column('item_a_id', sa.Integer(), nullable=False),
    sa.Column('item_b_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_a_id'], ['knowledge_item.knowledge_item_id'], ),
    sa.ForeignKeyConstraint(['item_b_id'], ['knowledge_item.knowledge_item_id'], ),
    sa.ForeignKeyConstraint(['knowledge_graph_id'], ['knowledge_graph.knowledge_graph_id'], ),
    sa.PrimaryKeyConstraint('knowledge_relation_id')
    )
    with op.batch_alter_table('knowledge_graph', schema=None) as batch_op:
        batch_op.drop_column('knowledge_graph_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_graph', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_graph_content', mysql.TEXT(), nullable=False))

    op.drop_table('knowledge_relation')
    op.drop_table('knowledge_item')
    # ### end Alembic commands ###
