"""empty message

Revision ID: 241bc200cde9
Revises: cb58890e0bad
Create Date: 2025-03-30 15:37:06.245790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '241bc200cde9'
down_revision = 'cb58890e0bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistaken_question', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('answer',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('similar_question',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('similar_answer',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistaken_question', schema=None) as batch_op:
        batch_op.alter_column('similar_answer',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('similar_question',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('answer',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
