"""empty message

Revision ID: 25bb0e045ad7
Revises: bc41d642a0c5
Create Date: 2025-02-18 23:06:52.852430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bb0e045ad7'
down_revision = 'bc41d642a0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('notes_chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notes_count')
        batch_op.drop_column('chapter_count')

    with op.batch_alter_table('notes_chapter', schema=None) as batch_op:
        batch_op.drop_column('notes_count')

    with op.batch_alter_table('chat_history_list', schema=None) as batch_op:
        batch_op.drop_column('chat_count')

    # ### end Alembic commands ###
