"""empty message

Revision ID: 26522fffac47
Revises: 25bb0e045ad7
Create Date: 2025-02-19 15:01:39.538831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26522fffac47'
down_revision = '25bb0e045ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes_chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clear_notes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vague_notes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unclear_notes_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clear_notes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vague_notes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unclear_notes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unclear_notes_count')
        batch_op.drop_column('vague_notes_count')
        batch_op.drop_column('clear_notes_count')

    with op.batch_alter_table('notes_chapter', schema=None) as batch_op:
        batch_op.drop_column('unclear_notes_count')
        batch_op.drop_column('vague_notes_count')
        batch_op.drop_column('clear_notes_count')

    # ### end Alembic commands ###
