"""empty message

Revision ID: 8c552157a0ef
Revises: ec2a18e73e11
Create Date: 2025-02-18 10:22:41.297870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c552157a0ef'
down_revision = 'ec2a18e73e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_list',
    sa.Column('chat_history_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_history_list_id')
    )
    op.create_table('notes_chapter',
    sa.Column('chapter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.create_table('advice',
    sa.Column('advice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advice_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['notes_chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('advice_id')
    )
    op.create_table('chat_history_detail',
    sa.Column('chat_history_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_describe', sa.Text(), nullable=True),
    sa.Column('words', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('system', 'user'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['notes_chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('chat_history_detail_id')
    )
    op.create_table('knowledge_graph',
    sa.Column('knowledge_graph_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_graph_content', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['notes_chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('knowledge_graph_id')
    )
    op.create_table('note',
    sa.Column('note_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_describe', sa.Text(), nullable=True),
    sa.Column('is_audio', sa.Boolean(), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('audio_describe', sa.Text(), nullable=True),
    sa.Column('words', sa.Text(), nullable=True),
    sa.Column('comprehension_level', sa.Enum('理解', '模糊', '不理解'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['notes_chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['notes_chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary')
    op.drop_table('note')
    op.drop_table('knowledge_graph')
    op.drop_table('chat_history_detail')
    op.drop_table('advice')
    op.drop_table('notes_chapter')
    op.drop_table('chat_history_list')
    # ### end Alembic commands ###
