"""empty message

Revision ID: 8e3ae1284c98
Revises: 22ba3a87ef65
Create Date: 2025-03-11 23:10:17.432186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3ae1284c98'
down_revision = '22ba3a87ef65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_summary',
    sa.Column('note_summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['notes_chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('note_summary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_summary')
    # ### end Alembic commands ###
