"""empty message

Revision ID: bc41d642a0c5
Revises: 8c552157a0ef
Create Date: 2025-02-18 11:34:55.449424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc41d642a0c5'
down_revision = '8c552157a0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_history_list_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('chat_history_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_history_list', ['chat_history_list_id'], ['chat_history_list_id'])
        batch_op.drop_column('chapter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_history_detail_ibfk_1', 'notes_chapter', ['chapter_id'], ['chapter_id'])
        batch_op.drop_column('chat_history_list_id')

    # ### end Alembic commands ###
