"""empty message

Revision ID: c9d8a18c2ea7
Revises: 241bc200cde9
Create Date: 2025-04-04 12:00:07.930436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d8a18c2ea7'
down_revision = '241bc200cde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistaken_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('error_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistaken_question', schema=None) as batch_op:
        batch_op.drop_column('error_type')
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
