"""empty message

Revision ID: cb58890e0bad
Revises: 4d015aae1c4c
Create Date: 2025-03-24 00:07:54.874556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb58890e0bad'
down_revision = '4d015aae1c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistaken_question_list',
    sa.Column('question_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('question_list_id')
    )
    op.create_table('mistaken_question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_list_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_describe', sa.Text(), nullable=True),
    sa.Column('similar_question', sa.Text(), nullable=False),
    sa.Column('similar_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_list_id'], ['mistaken_question_list.question_list_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mistaken_question')
    op.drop_table('mistaken_question_list')
    # ### end Alembic commands ###
