"""empty message

Revision ID: e62e70214231
Revises: c9d8a18c2ea7
Create Date: 2025-04-05 22:49:02.128205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e62e70214231'
down_revision = 'c9d8a18c2ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_category', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
